version: '3.8'
services:
  node:
    container_name: project_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3003:3003'
    volumes:
    - './backend-node/:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: project_mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - my-network
  react:
    container_name: front_react
    image: node:latest
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    working_dir: /home/node/app
    ports:
      - '3000:3000' 
    volumes:
      - './meeting:/home' # Expose React app's port
    networks:
      - my-network
networks:
  my-network:
    driver: bridge